### ISSUE TITLE
Fix non-working OpenStreetMaps button GUI

### ISSUE THREAD

**Issue by edoreld** [LAntoine/LAMSADE-tools#48]

**Comment by toshiro10** [comment]
It works : don't forget to use "retrieveGeocodeResponse()" method from the AddressInfos class for each AddressInfos before using the AddressInfos to instantiate ItineraryMap.
The AddressInfos constructor initialize its paramaters to empty (except the rawAddress attribute), we need to use retrieveGeocodeResponse() to set them. This was made in order to separate the treatments from the constructor. In one hand it would be better to add this method directly into the constructor but in the other hand it's more generic, for example GoogleItineraryMap only need the name of the address and not the longitude and latitude, so the retrieveGeocodeResponse() is useless for it.

For now I'll only add details in the AddressInfos constructor's doc and keep the current behavior but I'm 
more than open for discussion on that topic.

**Comment by edoreld** [comment]
Closed because reported as working. Reopen if needed.
